version: '3'
services:
  fastify-server:
    build:
      context: ./server
    ports:
      - '3000:8080'
    volumes:
      - ./server:/server
      - ./shared:/shared
    env_file:
      - ./server/.env
